[package]
name = "aml-lib"
version = "0.1.0"
authors = ["Claude Pilatre <..>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
url = "2.1.1"
base64 = "0.13.0"

[dev-dependencies]
hex = "0.4.2"
